spring:
  # Activate this for mysql
  #
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/spring_test
  #    username: topo
  #    password: 123
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQL8Dialect
  #
  # Activate this for mongodb
  data:
    mongodb:
      # Add the authSource parameter to the end of the URI
      uri: mongodb://master:123@localhost:27017/summer?authSource=admin


  # Scaling up your endpoints like microservices
  # Tell to spring what modules should be building
modules:
# exampleModule1: true
# exampleModule2: false

